### ISSUE TITLE
Remoção do 2.6 do nome do repositório

### ISSUE THREAD

**Issue by ViLourenco** [freterapido/freterapido_woocommerce_2.6#14]
Fala pessoal, tudo bem?
Seguinte, sugiro a remoção deste _2.6 do nome do repositório, pois dá a sensação que ele está desatualizado e incompatível com a versão 3.0.

Abs.

**Comment by davidalves1** [comment]
Ótima sugestão @ViLourenco. Isso já é feito no nosso módulo Magento. Iremos colocar as versões compatíveis na descrição do módulo
